FROM balenalib/rpi-raspbian:buster

RUN apt-get update -y
RUN apt-get install -y --no-install-recommends apt-utils build-essential python3-dev python3-pip libssl-dev libffi-dev python3-setuptools
RUN apt-get install -y python3-pil zlib1g-dev libjpeg-dev

RUN mkdir /opt/ishiki
COPY src /opt/ishiki/src
WORKDIR /opt/ishiki/src

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
# install dependencies
RUN pip3 install --extra-index-url https://www.piwheels.org/simple -r requirements.txt

RUN rm -rf /opt/ishiki
